server:
  port: 8123
  servlet:
    context-path: /api
yuapi:
  client:
    access-key: lhy
    secret-key: abcdefg

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  session:
    store-type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuapi
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
